server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://jpaela-database.cbs4aokwgb73.ap-northeast-2.rds.amazonaws.com:3306/jpaelastic
    username: admin
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



logiing:
  level:
    org.elasticsearch.client:TRACE